name: Develop

on:
  push:
    branches:
      - develop

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v2

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: andocodeando/infla-bot-dev:${{ env.SHORT_SHA }}

      - name: Install Railway CLI
        run: |
          curl -sL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | bash

      - name: Deploy to Railway
        run: |
          railway login --apiKey ${{ secrets.RAILWAY_TOKEN }}
          railway up --project infla-bot --service daring-creativity
