name: Development deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Tag image
        run: docker tag ${{secrets.DIGITALOCEAN_REGISTRY_NAME}}/infla-bot-dev \
          registry.digitalocean.com/${{secrets.DIGITALOCEAN_REGISTRY_NAME}}/infla-bot-dev:${{github.event.inputs.version }}

      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/${{secrets.DIGITALOCEAN_REGISTRY_NAME}}/infla-bot-dev:${{github.event.inputs.version }}
