name: Develop

on:
  push:
    branches:
      - develop

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v2

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set environment variables
        run: |
          rm .env || true
          echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> .env
          echo "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: andocodeando/infla-bot-dev:${{ env.SHORT_SHA }}
          build-args: |
            MYSQL_HOST=${{ secrets.MYSQL_HOST }}
            MYSQL_PORT=${{ secrets.MYSQL_PORT }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}

      - name: Remove environment variables
        run: |
          rm .env || true

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to DigitalOcean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSHKEY }}
          envs: GITHUB_SHA,${{env.SHORT_SHA}},${{secrets.NODE_PORT}},${{secrets.MYSQL_HOST}},${{secrets.MYSQL_PORT}},${{secrets.MYSQL_USER}},${{secrets.MYSQL_PASSWORD}},${{secrets.MYSQL_DATABASE}}
          script: |
            docker pull andocodeando/infla-bot-dev:${GITHUB_SHA::7}

            CURRENT_IMAGE=$(docker inspect -f '{{.Config.Image}}' app || true)

            docker stop app || true

            docker rm app || true

            docker rmi $CURRENT_IMAGE || true

            docker run -d --name app --restart on-failure -e NODE_PORT=${{secrets.NODE_PORT}} -e MYSQL_HOST=${{secrets.MYSQL_HOST}} -e MYSQL_PORT=${{secrets.MYSQL_PORT}} -e MYSQL_USER=${{secrets.MYSQL_USER}} -e MYSQL_PASSWORD=${{secrets.MYSQL_PASSWORD}} -e MYSQL_DATABASE=${{secrets.MYSQL_DATABASE}} -p ${{secrets.NODE_PORT}}:${{secrets.NODE_PORT}} andocodeando/infla-bot-dev:${GITHUB_SHA::7}
