name: Develop

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v2

      - name: Install Railway CLI
        run: |
          curl -sL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | bash
      
      - name: Set Railway Token
        run: echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}" >> $GITHUB_ENV
      
      - name: Deploy to Railway
        env:
          MYSQL_HOST: ${{secrets.MYSQL_HOST}}
          MYSQL_PORT: ${{secrets.MYSQL_PORT}}
          MYSQL_USER: ${{secrets.MYSQL_USER}}
          MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
          MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}
        run: |
          railway up --service daring-creativity
