name: Develop

on:
  push:
    branches:
      - develop

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v2

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          file: Dockerfile
          push: true
          tags: andocodeando/infla-bot-dev:${{ env.SHORT_SHA }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to DigitalOcean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSHKEY }}
          envs: GITHUB_SHA,${{env.SHORT_SHA}},${{ secrets.NODE_PORT }},${{ secrets.MYSQL_HOST }},${{ secrets.MYSQL_PORT }},${{ secrets.MYSQL_USER }},${{ secrets.MYSQL_PASSWORD }},${{ secrets.MYSQL_DATABASE }}
          script: |
            docker pull andocodeando/infla-bot-dev:${GITHUB_SHA::7}

            docker stop app || true

            docker rm app || true

            docker run -d \
              -e NODE_PORT=$NODE_PORT \
              -e MYSQL_HOST=$MYSQL_HOST \
              -e MYSQL_PORT=$MYSQL_PORT \
              -e MYSQL_USER=$MYSQL_USER \
              -e MYSQL_PASSWORD=$MYSQL_PASSWORD \
              -e MYSQL_DATABASE=$MYSQL_DATABASE \
              -p $NODE_PORT:$NODE_PORT \
            --name app \
            --restart on-failure \
            andocodeando/infla-bot-dev:${GITHUB_SHA::7}
