name: Develop

on:
  push:
    branches:
      - develop

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v2

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: andocodeando/infla-bot-dev:${{ env.SHORT_SHA }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to DigitalOcean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSHKEY }}
          envs: GITHUB_SHA,${{env.SHORT_SHA}}
          script: |
            docker pull andocodeando/infla-bot-dev:${GITHUB_SHA::7}

            docker stop app || true

            docker rm app || true

            docker run -d --name app --restart on-failure -p ${{secrets.NODE_PORT}}:${{secrets.NODE_PORT}} andocodeando/infla-bot-dev:${GITHUB_SHA::7}
