name: Development deploy

on:
  push:
    branches:
      - develop

  workflow_dispatch:
    inputs:
      version:
        description: "Image version"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN}}

      - name: Deploy to DigitalOcean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSHKEY }}
          script: |
            cd /home/app

            git clone git@github.com:GermanTorales/infla-bot.git

            echo 'Deployment to digital ocean finished'
